package com.xp.mybatisboot.pojo;

public class Wxinfo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wxinfo.openid
     *
     * @mbggenerated Tue Jun 02 16:21:13 CST 2020
     */
    private String openid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wxinfo.nickname
     *
     * @mbggenerated Tue Jun 02 16:21:13 CST 2020
     */
    private String nickname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wxinfo.area
     *
     * @mbggenerated Tue Jun 02 16:21:13 CST 2020
     */
    private String area;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wxinfo.pictrue
     *
     * @mbggenerated Tue Jun 02 16:21:13 CST 2020
     */
    private String pictrue;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wxinfo.sex
     *
     * @mbggenerated Tue Jun 02 16:21:13 CST 2020
     */
    private String sex;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wxinfo.datamd5
     *
     * @mbggenerated Tue Jun 02 16:21:13 CST 2020
     */
    private String datamd5;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wxinfo.openid
     *
     * @return the value of wxinfo.openid
     *
     * @mbggenerated Tue Jun 02 16:21:13 CST 2020
     */
    public String getOpenid() {
        return openid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wxinfo.openid
     *
     * @param openid the value for wxinfo.openid
     *
     * @mbggenerated Tue Jun 02 16:21:13 CST 2020
     */
    public void setOpenid(String openid) {
        this.openid = openid == null ? null : openid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wxinfo.nickname
     *
     * @return the value of wxinfo.nickname
     *
     * @mbggenerated Tue Jun 02 16:21:13 CST 2020
     */
    public String getNickname() {
        return nickname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wxinfo.nickname
     *
     * @param nickname the value for wxinfo.nickname
     *
     * @mbggenerated Tue Jun 02 16:21:13 CST 2020
     */
    public void setNickname(String nickname) {
        this.nickname = nickname == null ? null : nickname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wxinfo.area
     *
     * @return the value of wxinfo.area
     *
     * @mbggenerated Tue Jun 02 16:21:13 CST 2020
     */
    public String getArea() {
        return area;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wxinfo.area
     *
     * @param area the value for wxinfo.area
     *
     * @mbggenerated Tue Jun 02 16:21:13 CST 2020
     */
    public void setArea(String area) {
        this.area = area == null ? null : area.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wxinfo.pictrue
     *
     * @return the value of wxinfo.pictrue
     *
     * @mbggenerated Tue Jun 02 16:21:13 CST 2020
     */
    public String getPictrue() {
        return pictrue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wxinfo.pictrue
     *
     * @param pictrue the value for wxinfo.pictrue
     *
     * @mbggenerated Tue Jun 02 16:21:13 CST 2020
     */
    public void setPictrue(String pictrue) {
        this.pictrue = pictrue == null ? null : pictrue.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wxinfo.sex
     *
     * @return the value of wxinfo.sex
     *
     * @mbggenerated Tue Jun 02 16:21:13 CST 2020
     */
    public String getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wxinfo.sex
     *
     * @param sex the value for wxinfo.sex
     *
     * @mbggenerated Tue Jun 02 16:21:13 CST 2020
     */
    public void setSex(String sex) {
        this.sex = sex == null ? null : sex.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wxinfo.datamd5
     *
     * @return the value of wxinfo.datamd5
     *
     * @mbggenerated Tue Jun 02 16:21:13 CST 2020
     */
    public String getDatamd5() {
        return datamd5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wxinfo.datamd5
     *
     * @param datamd5 the value for wxinfo.datamd5
     *
     * @mbggenerated Tue Jun 02 16:21:13 CST 2020
     */
    public void setDatamd5(String datamd5) {
        this.datamd5 = datamd5 == null ? null : datamd5.trim();
    }
}