package com.xp.mybatisboot.mapper;

import com.xp.mybatisboot.pojo.Wxinfo2;

import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface Wxinfo2Mapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wxinfo2
     *
     * @mbggenerated Tue Jun 02 16:27:06 CST 2020
     */
    int countByExample(Wxinfo2Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wxinfo2
     *
     * @mbggenerated Tue Jun 02 16:27:06 CST 2020
     */
    int deleteByExample(Wxinfo2Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wxinfo2
     *
     * @mbggenerated Tue Jun 02 16:27:06 CST 2020
     */
    int deleteByPrimaryKey(String openid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wxinfo2
     *
     * @mbggenerated Tue Jun 02 16:27:06 CST 2020
     */
    int insert(Wxinfo2 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wxinfo2
     *
     * @mbggenerated Tue Jun 02 16:27:06 CST 2020
     */
    int insertSelective(Wxinfo2 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wxinfo2
     *
     * @mbggenerated Tue Jun 02 16:27:06 CST 2020
     */
    List<Wxinfo2> selectByExample(Wxinfo2Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wxinfo2
     *
     * @mbggenerated Tue Jun 02 16:27:06 CST 2020
     */
    Wxinfo2 selectByPrimaryKey(String openid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wxinfo2
     *
     * @mbggenerated Tue Jun 02 16:27:06 CST 2020
     */
    int updateByExampleSelective(@Param("record") Wxinfo2 record, @Param("example") Wxinfo2Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wxinfo2
     *
     * @mbggenerated Tue Jun 02 16:27:06 CST 2020
     */
    int updateByExample(@Param("record") Wxinfo2 record, @Param("example") Wxinfo2Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wxinfo2
     *
     * @mbggenerated Tue Jun 02 16:27:06 CST 2020
     */
    int updateByPrimaryKeySelective(Wxinfo2 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wxinfo2
     *
     * @mbggenerated Tue Jun 02 16:27:06 CST 2020
     */
    int updateByPrimaryKey(Wxinfo2 record);
}
